
<!-- Modal -->
<div id="myModal" class="modal fade">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title white">{$smarty.const.SITE_URL|substr:7} Terms of Use Agreement</h4>
        </div>
      <div class="modal-body"  id="draftedplayers">
        <div>
  <i>Effective on 2021-02-08</i>
  <p>California subscribers: You may cancel your subscription, without penalty or obligation, at any time prior to midnight of the third business day following the date you subscribed. If you subscribed using an External Service (e.g., Apple ID, Google Play), you must cancel through your External Service, as set forth in more detail in Section 8a.  If you subscribed through your Apple ID, refunds are handled by Apple/Google, not {$smarty.const.SITE_NAME}. You can request a refund from Apple through your Apple ID account on your phone or at https://getsupport.apple.com.  All other users may request a refund by contacting {$smarty.const.SITE_NAME} Customer Service at by clicking <a href="/help/contactus.aspx">here</a>, or by mailing or delivering a signed and dated notice that states that you, the buyer, are canceling this agreement, or words of similar effect. Please also include your name and the email address, phone number, or other unique identifier you used to sign up for your account. This notice shall be sent to: {$smarty.const.SITE_NAME}, Attn: Cancellations, P.O. Box 25472, Dallas, Texas 75225, USA. The Company’s business is conducted, in part, at 8750 N. Central Expressway, Suite 1400, Dallas, TX 75205. You may have these terms of use e-mailed to you by sending a letter to Terms Inquiries, P.O. Box 25472, Dallas, Texas 75225, USA. In accordance with Cal. Civ. Code §1789.3, you may report complaints to the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by contacting them in writing at Consumer Information Division, 1625 North Market Blvd., Suite N112 Sacramento, CA 95834, or by telephone at (800) 952-5210.</p>
  <p><strong><i>We have included brief summaries at the beginning of each section to make it easier for you to read and understand this agreement. The summaries do not replace the text of each section, and you should still read each section in its entirety.   </i></strong></p>
  <h2>1. INTRODUCTION</h2>
  <p><strong><i>By accessing or using {$smarty.const.SITE_NAME}’s services, you agree to be bound by these terms, including our <a href="/legalpolicy/privacypolicy">Privacy</a> and <a href="/legalpolicy/cookiepolicy">Cookie</a> Policies, so it is important that you read this agreement carefully before you create an account. We may update the terms from time to time, so you should check this page regularly for updates.</i></strong></p>
  <p>Welcome to {$smarty.const.SITE_NAME}, operated by {$smarty.const.SITE_NAME} Group, LLC, in the case of users originating from within the United States and Canada, and {$smarty.const.SITE_URL|substr:7} Global Services Limited, in the case of users originating from outside of the United States and Canada. As used in this Agreement, the terms “{$smarty.const.SITE_NAME},” “us,” “we,” the “Company”, and “our” shall refer to {$smarty.const.SITE_NAME} Group, LLC and/or {$smarty.const.SITE_URL|substr:7} Global Services Limited, as appropriate.</p>
  <p>By accessing or using our Services on {$smarty.const.SITE_URL|substr:7} (the “Website”), the {$smarty.const.SITE_NAME} mobile application (the “App”), or any other platforms or services {$smarty.const.SITE_NAME} may offer (collectively, the “Service” or our “Services”), you agree to, and are bound by, these Terms of Use (the “Terms” or “Agreement”). This Agreement applies to anyone who accesses or uses our Services, regardless of registration or subscription status. </p>
  <p>Your use of our Services is also subject to the <a href="/legalpolicy/privacypolicy">Privacy Policy</a>,  <a href="/legalpolicy/cookiepolicy">Cookie Policy</a>, and any terms disclosed and agreed to by you when you purchase additional features, products, or services from {$smarty.const.SITE_NAME} (“Additional Terms Upon Purchase”), which are incorporated into this Agreement by reference. If you do not wish to be bound by this Agreement, do not use our Services.</p>
  <p>We reserve the right to modify, amend, or change the Terms at any time. Notice of any material change will be posted on this page with an updated effective date. In certain circumstances, we may notify you of a change to the Terms via email or other means, as appropriate under the circumstances; however, you are responsible for regularly checking this page for notice of any changes. We agree that future changes will not be retroactive without your consent. Your continued use of our Services constitutes your acceptance of any change, and you will be legally bound by the updated Terms. If you do not accept a change to the terms, you should stop using our Services immediately. </p>
  <h2>2.	ACCOUNT ELIGIBILITY; YOUR RESPONSIBILITIES </h2>
  <p><strong><i>Before you create an account on {$smarty.const.SITE_NAME}, make sure you are eligible to use our Services.  This Section also details what you can and can’t do when using the Services, as well as the rights you grant {$smarty.const.SITE_NAME}.</i></strong></p>
  <p><strong>By using our Services, you represent and warrant that:</strong></p>
  <ul>
    <li>You are at least 18 years old; </li>
    <li>You are legally qualified to enter a binding contract with {$smarty.const.SITE_NAME};</li>
    <li>You are single or separated from your spouse; </li>
    <li>You are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country;</li>
    <li>You are not on any list of individuals prohibited from conducting business with the United States;</li>
    <li>You are not prohibited by law from using our services; </li>
    <li>You have not have been convicted of or pled no contest to a felony or indictable offense (or crime of similar severity), a sex crime, or any crime involving violence;</li>
    <li>You are not required to register as a sex offender with any state, federal or local sex offender registry; </li>
    <li>You do not have more than one account on our Services; and</li>
    <li>You have not previously been removed from our Services by us, unless you have our express written permission to create a new account. </li>
  </ul>
  <p>If at any time you cease to meet these requirements, you must immediately delete your account.</p>
  <p><strong>You agree to:</strong></p>
  <ul class="bullet">
    <li>Comply with these Terms, and check this page from time to time to ensure you are aware of any change;</li>
    <li>Comply with all applicable laws, including without limitation, privacy laws, intellectual property laws, anti-spam laws, and regulatory requirements;</li>
    <li>Use the latest version of the Website and/or App;</li>
    <li>Treat other users in a courteous and respectful manner, both on and off our Services;</li>
    <li>Be respectful when communicating with any of our customer care representatives or other employees;</li>
    <li>Review the <a href="/help/safetytips.aspx?lid=4">Safety Tips</a>; </li>
    <li>Maintain a strong password and take reasonable measures to protect the security of your login information.</li>
  </ul>
  <p><strong>You agree that you will not:</strong></p>
  <ul class="bullet">
    <li>Misrepresent your identity, age, current or previous positions, qualifications, or affiliations with a person or entity;</li>
    <li>Use the Services in a way that damages the Services or prevents their use by other users;</li>
    <li>Use our Services in a way to interfere with, disrupt or negatively affect the platform, the servers, or our Services’ networks;</li>
    <li>Use our Services for any harmful, illegal, or nefarious purpose;</li>
    <li>Harass, bully, stalk, intimidate, assault, defame, harm or otherwise mistreat any person;</li>
    <li>Post or share Prohibited Content (see below);</li>
    <li>Solicit passwords for any purpose, or personal identifying information for commercial or unlawful purposes from other users or disseminate another person’s personal information without his or her permission;</li>
    <li>Solicit money or other items of value from another user, whether as a gift, loan, or form of compensation;</li>
    <li>Use another user’s account;</li>
    <li>Use our Services in relation to fraud, a pyramid scheme, or other similar practice; or</li>
    <li>Violate the terms of the license granted to you by {$smarty.const.SITE_NAME} (see Section 6 below).</li>
    <li>Disclose private or proprietary information that you do not have the right to disclose;</li>
    <li>Copy, modify, transmit, distribute, or create any derivative works from, any Member Content or Our Content, or any copyrighted material, images, trademarks, trade names, service marks, or other intellectual property, content or proprietary information accessible through our Services without {$smarty.const.SITE_NAME}’s prior written consent;</li>
    <li>Express or imply that any statements you make are endorsed by {$smarty.const.SITE_NAME};</li>
    <li>Use any robot, crawler, site search/retrieval application, proxy or other manual or automatic device, method or process to access, retrieve, index, “data mine,” or in any way reproduce or circumvent the navigational structure or presentation of our Services or its contents;</li>
    <li>Upload viruses or other malicious code or otherwise compromise the security of our Services;</li>
    <li>Forge headers or otherwise manipulate identifiers to disguise the origin of any information transmitted to or through our Services;</li>
    <li>“Frame” or “mirror” any part of our Services without {$smarty.const.SITE_NAME}’s prior written authorization;</li>
    <li>Use meta tags or code or other devices containing any reference to {$smarty.const.SITE_NAME} or the platform (or any trademark, trade name, service mark, logo or slogan of {$smarty.const.SITE_NAME}) to direct any person to any other website for any purpose;</li>
    <li>Modify, adapt, sublicense, translate, sell, reverse engineer, decipher, decompile or otherwise disassemble any portion of our Services, or cause others to do so;</li>
    <li>Use or develop any third-party applications that interact with our Services or Member Content or information without our written consent;</li>
    <li>Use, access, or publish the {$smarty.const.SITE_NAME} application programming interface without our written consent;</li>
    <li>Probe, scan or test the vulnerability of our Services or any system or network; or</li>
    <li>Encourage, promote, or agree to engage in any activity that violates these Terms.</li>
  </ul>
  <p><strong>Prohibited Content—{$smarty.const.SITE_NAME} prohibits uploading or sharing content that:</strong></p>
  <ul class="bullet">
    <li>Is likely to be deemed offensive or to harass, upset, embarrass, alarm or annoy any other person; </li>
    <li>Is obscene, pornographic, violent or otherwise may offend human dignity, or contains nudity;</li>
    <li>Is abusive, insulting or threatening, discriminatory or that promotes or encourages racism, sexism, hatred or bigotry;</li>
    <li>Encourages or facilitates any illegal activity including, without limitation, terrorism, inciting racial hatred or the submission of which in itself constitutes committing a criminal offense;</li>
    <li>Is defamatory, libelous, or untrue;</li>
    <li>Relates to commercial activities (including, without limitation, sales, competitions, promotions, and advertising, solicitation for services, “sugar daddy” or “sugar baby” relationships, links to other websites or premium line telephone numbers);</li>
    <li>Involves the transmission of “junk” mail or “spam”;</li>
    <li>Contains any spyware, adware, viruses, corrupt files, worm programs or other malicious code designed to interrupt, damage or limit the functionality of or disrupt any software, hardware, telecommunications, networks, servers or other equipment, Trojan horse or any other material designed to damage, interfere with, wrongly intercept or expropriate any data or personal information whether from {$smarty.const.SITE_NAME} or otherwise;</li>
    <li>Infringes upon any third party’s rights (including, without limitation, intellectual property rights and privacy rights); </li>
    <li>Was not written by you or was automatically generated, unless expressly authorized by {$smarty.const.SITE_NAME};</li>
    <li>Includes the image or likeness of another person without that person’s consent (or in the case of a minor, the minor’s parent or guardian), or is an image or likeness or a minor unaccompanied by the minor’s parent or guardian; </li>
    <li>Is inconsistent with the intended use of the Services; or</li>
    <li>May harm the reputation of {$smarty.const.SITE_NAME} or its affiliates.</li>
  </ul>
  <p>The uploading or sharing of content that violates these terms (“Prohibited Content”) may result in the immediate suspension or termination of your account.  </p>
  <h2>3.	CONTENT </h2>
  <p><strong><i>It is important that you understand your rights and responsibilities with regard to the content on our Services, including any content you provide or post.  You are expressly prohibited from posting inappropriate content.</i></strong></p>
  <p>While using our Services, you will have access to: (i) content that you upload or provide while using our Services (“Your Content”); (ii) content that other users upload or provide while using our Services (“Member Content”); and (iii) content that {$smarty.const.SITE_NAME} provides on and through our Services (“Our Content”). In this agreement, “content” includes, without limitation, all text, images, video, audio, or other material on our Services, including information on users’ profiles and in direct messages between users.</p>
  <h2>3a.	YOUR CONTENT</h2>
  <p><strong><i>You are responsible for Your Content. Don’t share anything that you wouldn’t want others to see, that would violate this Agreement, or that may expose you or us to legal liability. </i></strong></p>
  <p>You are solely responsible and liable for Your Content, and, therefore, you agree to indemnify, defend, release, and hold us harmless from any claims made in connection with Your Content. </p>
  <p>You represent and warrant to us that the information you provide to us or any other user is accurate, including any information submitted through Facebook or other third-party sources (if applicable), and that you will update your account information as necessary to ensure its accuracy. </p>
  <p>The content included on your individual profile should be relevant to the intended use of our Services. You may not display any personal contact or banking information, whether in relation to you or any other person (for example, names, home addresses or postcodes, telephone numbers, email addresses, URLs, credit/debit card or other banking details). If you choose to reveal any personal information about yourself to other users, you do so at your own risk. We encourage you to use caution in disclosing any personal information online.</p>
  <p>Your individual profile will be visible to other people around the world, so be sure that you are comfortable sharing Your Content before you post. You acknowledge and agree that Your Content may be viewed by other users, and, notwithstanding these Terms, other users may share Your Content with third parties. By uploading Your Content, you represent and warrant to us that you have all necessary rights and licenses to do so and automatically grant us a license to use Your Content as provided under Section 7 below. </p>
  <p>You understand and agree that we may monitor or review Your Content, and we have the right to remove, delete, edit, limit, or block or prevent access to any of Your Content at any time in our sole discretion. Furthermore, you understand agree that we have no obligation to display or review Your Content.  </p>
  <h2>3b.	MEMBER CONTENT</h2>
  <p><strong><i>While you will have access to Member Content, it is not yours and you may not copy or use Member Content for any purpose except as contemplated by these Terms.</i></strong></p>
  <p>Other users will also share content on our Services. Member Content belongs to the user who posted the content and is stored on our servers and displayed at the direction of that user.</p>
  <p>You do not have any rights in relation to Member Content, and you may only use Member Content to the extent that your use is consistent with our Services’ purpose of allowing use to communicate with and meet one another. You may not copy the Member Content or use Member Content for commercial purposes, to spam, to harass, or to make unlawful threats. We reserve the right to terminate your account if you misuse Member Content.</p>
  <h2>3c.	OUR CONTENT </h2>
  <p><strong><i>{$smarty.const.SITE_NAME} owns all other content on our Services. </i></strong></p>
  <p>Any other text, content, graphics, user interfaces, trademarks, logos, sounds, artwork, images, and other intellectual property appearing on our Services is owned, controlled or licensed by us and protected by copyright, trademark and other intellectual property law rights. All rights, title, and interest in and to Our Content remains with us at all times.</p>
  <p>We grant you a limited license to access and use Our Content as provided under Section 6 below, and we reserve all other rights.</p>
  <h2>4.	INAPPROPRIATE CONTENT AND MISCONDUCT; REPORTING</h2>
  <p><strong><i>{$smarty.const.SITE_NAME} does not tolerate inappropriate content or behavior on our Services. </i></strong></p>
  <p>We are committed to maintaining a positive and respectful {$smarty.const.SITE_NAME} community, and we do not tolerate any inappropriate content or misconduct, whether on or off of the Services. We encourage you to report any inappropriate Member Content or misconduct by other users. You can report a user directly through the “Report a Concern” link on a user’s profile or at the bottom of every email. You may also email {$smarty.const.SITE_NAME} Customer Service by clicking <a href="/help/contactus.aspx">here</a>. </p>
  <p>Member Content is subject to the terms and conditions of Sections 512(c) and/or 512(d) of the Digital Millennium Copyright Act 1998. To submit a complaint regarding Member Content that may constitute intellectual property infringement, see Section 12 (Digital Millennium Copyright Act) below.</p>
  <h2>5.	PRIVACY </h2>
  <p><strong><i>Privacy is important to us. We have a separate policy about it that you should read.</i></strong></p>
  <p>For information about how {$smarty.const.SITE_NAME} and its affiliates collect, use, and share your personal data, please read our <a href="/legalpolicy/privacypolicy">Privacy Policy</a> . By using our Services, you agree that we may use your personal data in accordance with our <a href="/legalpolicy/privacypolicy">Privacy Policy</a> . </p>
  <h2>6.	RIGHTS YOU ARE GRANTED BY {$smarty.const.SITE_NAME} </h2>
  <p><strong><i>{$smarty.const.SITE_NAME} grants you the right to use and enjoy our Services, subject to these Terms.</i></strong></p>
  <p>For as long as you comply with these Terms, {$smarty.const.SITE_NAME} grants you a personal, worldwide, royalty-free, non-assignable, non-exclusive, revocable, and non-sublicensable license to access and use our Services for purposes as intended by {$smarty.const.SITE_NAME} and permitted by these Terms and applicable laws.</p>
  <h2>7.	RIGHTS YOU GRANT {$smarty.const.SITE_NAME} </h2>
  <p><strong><i>You own all of the content you provide to {$smarty.const.SITE_NAME}, but you also grant us the right to use Your Content as provided in this Agreement.</i></strong></p>
  <p>By creating an account, you grant to {$smarty.const.SITE_NAME} a worldwide, perpetual, transferable, sub-licensable, royalty-free right and license to host, store, use, copy, display, reproduce, adapt, edit, publish, translate, modify, and distribute Your Content, including any information you authorize us to access from Facebook or other third-party source (if applicable), in whole or in part, and in any format or medium currently known or developed in the future. {$smarty.const.SITE_NAME}’s license to Your Content shall be non-exclusive, except that {$smarty.const.SITE_NAME}’s license shall be exclusive with respect to derivative works created through use of our Services. For example, {$smarty.const.SITE_NAME} would have an exclusive license to screenshots of our Services that include Your Content. </p>
  <p>In addition, so that {$smarty.const.SITE_NAME} can prevent the use of Your Content outside of our Services, you authorize {$smarty.const.SITE_NAME} to act on your behalf with respect to infringing uses of Your Content taken from our Services by other users or third parties. This expressly includes the authority, but not the obligation, to send notices pursuant to 17 U.S.C. § 512(c)(3) (i.e., DMCA Takedown Notices) on your behalf if Your Content is taken and used by third parties outside of our Services. {$smarty.const.SITE_NAME} is not obligated to take any action with regard to use of Your Content by other users or third parties. {$smarty.const.SITE_NAME}’s license to Your Content is subject to your rights under applicable law (for example, laws regarding personal data protection to the extent the content contains personal information as defined by those laws). </p>
  <p>In consideration for {$smarty.const.SITE_NAME} allowing you to use our Services, you agree that we, our affiliates, and our third-party partners may place advertising on our Services. By submitting suggestions or feedback to {$smarty.const.SITE_NAME} regarding our Services, you agree that {$smarty.const.SITE_NAME} may use and share such feedback for any purpose without compensating you.</p>
  <p>You agree that {$smarty.const.SITE_NAME} may access, preserve, and disclose your account information, including Your Content, if required to do so by law or upon a good faith belief that such access, preservation, or disclosure is reasonably necessary to: (i) comply with legal process; (ii) enforce these Terms; (iii) respond to claims that any content violates the rights of third parties; (iv) respond to your requests for customer service; or (v) protect the rights, property or personal safety of the Company or any other person.</p>
  <h2 class="red">8.	PURCHASES AND AUTOMATICALLY RENEWING SUBSCRIPTIONS</h2>
  <p><strong><i>You will have the opportunity to purchase products and services from {$smarty.const.SITE_NAME}. If you purchase a subscription, it will automatically renew—and you will be charged—until you cancel.</i></strong></p>
  <p>
    {$smarty.const.SITE_NAME} may offer products and services for purchase through iTunes, Google Play or other external services authorized by {$smarty.const.SITE_NAME} (each, an “External Service,” and any purchases made thereon, an “External Service Purchase”). {$smarty.const.SITE_NAME} may also offer products and services for purchase via credit card or other payment processors on the Website or inside the App (“Internal Purchases”). 
    <span class="red">If you purchase a subscription, it will automatically renew until you cancel, in accordance with the terms disclosed to you at the time of purchase, as further described below</span>.
    If you cancel your subscription, you will continue to have access to your subscription benefits until the end of your subscription period, at which point it will expire.
  </p>
  <p>Because our Services may be utilized without a subscription, canceling your subscription does not remove your profile from our Services.  If you wish to fully terminate your membership, you must terminate your membership as set forth in Section 9.</p>
  <h2 class="red">8a. EXTERNAL SERVICE PURCHASES AND SUBSCRIPTIONS </h2>
  <p><strong><i>External Service Purchases, including subscriptions, may be processed through the External Service, in which case those purchases must be managed through your External Service Account.  Subscriptions automatically renew until you cancel.</i></strong></p>
  <p>When making a purchase on the Service, you may have the option to pay through an External Service, such as with your Apple ID or Google account (“your External Service Account”), and your External Service Account will be charged for the purchase in accordance with the terms disclosed to you at the time of purchase and the general terms applicable to your External Service Account. Some External Services may charge you sales tax, depending on where you live, which may change from time to time. </p>
  <p class="red">If your External Service Purchase includes an automatically renewing subscription, your External Service Account will continue to be periodically charged for the subscription until you cancel. After your initial subscription commitment period, and again after any subsequent subscription period, the subscription will automatically continue for the price and time period you agreed to when subscribing. </p>
  <p class="red"><span class="underline">To cancel a subscription</span>: If you do not want your subscription to renew automatically, or if you want to change or terminate your subscription, you must log in to your External Service Account and follow instructions to manage or cancel your subscription, even if you have otherwise deleted your account with us or if you have deleted the App from your device.  For example, if you subscribed using your Apple ID, cancellation is handled by Apple, not {$smarty.const.SITE_NAME}. To cancel a purchase made with your Apple ID, go to Settings > iTunes & App Stores > [click on your Apple ID] > View Apple ID > Subscriptions, then find your {$smarty.const.SITE_NAME} subscription and follow the instructions to cancel. You can also request assistance at https://getsupport.apple.com. Similarly, if you subscribed on Google Play, cancellation is handled by Google.  To cancel a purchase made through Google Play, launch the Google Play app on your mobile device and go to Menu > My Apps > Subscriptions, then find your {$smarty.const.SITE_NAME} subscription and follow the instructions to cancel. You can also request assistance at https://play.google.com.  If you cancel a subscription, you may continue to use the cancelled service until the end of your then-current subscription term. The subscription will not be renewed when your then-current term expires.</p>
  <p>If you initiate a chargeback or otherwise reverse a payment made with your External Service Account, {$smarty.const.SITE_NAME} may terminate your account immediately in its sole discretion, on the basis that you have determined that you do not want a {$smarty.const.SITE_NAME} subscription.  In the event that your chargeback or other payment reversal is overturned, please contact <a href="/faq/contactus">Customer Care</a>. {$smarty.const.SITE_NAME} will retain all funds charged to your External Service Account until you cancel your subscription through your External Service Account. Certain users may be entitled to request a refund. See Section 8d below for more information.</p>
  <h2 class="red">8b. INTERNAL PURCHASES AND SUBSCRIPTIONS</h2>
  <p><strong><i>Internal Purchases, including subscriptions, are processed using the Payment Method you provide on the Website or App.  Subscriptions automatically renew until you cancel.</i></strong></p>
  <p>If you make an Internal Purchase, you agree to pay the prices displayed to you for the Services you’ve selected as well as any sales or similar taxes that may be imposed on your payments (and as may change from time to time), and you authorize {$smarty.const.SITE_NAME} to charge the payment method you provide (your “Payment Method”). {$smarty.const.SITE_NAME} may correct any billing errors or mistakes even if we have already requested or received payment. If you initiate a chargeback or otherwise reverse a payment made with your Payment Method, {$smarty.const.SITE_NAME} may terminate your account immediately in its sole discretion, on the basis that you have determined that you do not want a {$smarty.const.SITE_NAME} subscription.  In the event that your chargeback or other payment reversal is overturned, please contact <a href="/faq/contactus">Customer Care</a>.</p>
  <p class="red">If your Internal Purchase includes an automatically renewing subscription, your Payment Method will continue to be periodically charged for the subscription until you cancel. After your initial subscription commitment period, and again after any subsequent subscription period, your subscription will automatically continue for the price and time period you agreed to when subscribing, until you cancel. </p>
  <p class="red">To cancel a subscription, log in to the Website and go to the Settings tool. If you cancel a subscription, you may continue to use the cancelled service until the end of your then-current subscription term. The subscription will not be renewed when your then-current term expires.</p>
  <p>You may edit your Payment Method information by using the Settings tool. If a payment is not successfully processed, due to expiration, insufficient funds, or otherwise, you remain responsible for any uncollected amounts and authorize us to continue billing the Payment Method, as it may be updated. This may result in a change to your payment billing dates. </p>
  <p>In addition, you authorize us to obtain updated or replacement expiration dates and card numbers for your credit or debit card as provided by your credit or debit card issuer. The terms of your payment will be based on your Payment Method and may be determined by agreements between you and the financial institution, credit card issuer, or other provider of your chosen Payment Method. Certain users may be entitled to request a refund. See Section 8d below for more information.</p>
  <h2>8c. VIRTUAL ITEMS </h2>
  <p><strong><i>Virtual items are non-refundable and subject to certain conditions.</i></strong></p>
  <p>From time to time, you may have the opportunity purchase a limited, personal, non-transferable, non-sublicensable, revocable license to use or access special limited-use features such as “Boost” (“Virtual Item(s)”) from {$smarty.const.SITE_NAME}. You may only purchase Virtual Items from us or our authorized partners through our Services. Virtual Items represent a limited license right governed by this Agreement, and, except as otherwise prohibited by applicable law, no title or ownership in or to Virtual Items is being transferred or assigned to you. This Agreement should not be construed as a sale of any rights in Virtual Items. </p>
  <p>Any Virtual Item balance shown in your account does not constitute a real-world balance or reflect any stored value, but instead constitutes a measurement of the extent of your license. Virtual Items do not incur fees for non-use; however, the license granted to you in Virtual Items will terminate in accordance with the terms of this Agreement, on the earlier of when {$smarty.const.SITE_NAME} ceases providing our Services, or your account is otherwise closed or terminated. </p>
  <p>{$smarty.const.SITE_NAME}, in its sole discretion, reserves the right to charge fees for the right to access or use Virtual Items and/or may distribute Virtual Items with or without charge. {$smarty.const.SITE_NAME} may manage, regulate, control, modify, or eliminate Virtual Items at any time, including taking actions that may impact the perceived value or purchase price, if applicable, of any Virtual Items. {$smarty.const.SITE_NAME} shall have no liability to you or any third party in the event that {$smarty.const.SITE_NAME} exercises any such rights. The transfer of Virtual Items is prohibited, and you shall not sell, redeem, or otherwise transfer Virtual Items to any person or entity. Virtual Items may only be redeemed through our Services. </p>
  <p>ALL PURCHASES AND REDEMPTIONS OF VIRTUAL ITEMS MADE THROUGH OUR SERVICES ARE FINAL AND NON-REFUNDABLE. YOU ACKNOWLEDGE THAT {$smarty.const.SITE_NAME} IS NOT REQUIRED TO PROVIDE A REFUND FOR ANY REASON, AND THAT YOU WILL NOT RECEIVE MONEY OR OTHER COMPENSATION FOR UNUSED VIRTUAL ITEMS WHEN AN ACCOUNT IS CLOSED, WHETHER SUCH CLOSURE WAS VOLUNTARY OR INVOLUNTARY.</p>
  <h2>8d. REFUNDS</h2>
  <p><strong><i>Generally, all purchases are nonrefundable. Special terms apply in Arizona, California, Connecticut, Illinois, Iowa, Minnesota, New York, North Carolina, Ohio, Rhode Island, and Wisconsin.</i></strong></p>
  <p>Generally, all purchases are final and nonrefundable, and there are no refunds or credits for partially used periods, except if the laws applicable in your jurisdiction provide for refunds.</p>
  <p class="underline">For subscribers residing in Arizona, California, Connecticut, Illinois, Iowa, Minnesota, New York, North Carolina, Ohio, Rhode Island, and Wisconsin:</p>
  <p><strong>Your Right to Cancel—You may cancel your subscription, without penalty or obligation, at any time prior to midnight of the third business day following the date you subscribed.</strong>In the event that you die before the end of your subscription period, your estate shall be entitled to a refund of that portion of any payment you had made for your subscription which is allocable to the period after your death. In the event that you become disabled (such that you are unable to use our Services) before the end of your subscription period, you shall be entitled to a refund of that portion of any payment you had made for your subscription which is allocable to the period after your disability by providing the company notice in the same manner as you request a refund as described below.</p>
  <p>Purchases of Virtual Items are FINAL AND NON-REFUNDABLE.</p>
  <p>If any of the above apply to you and you subscribed using your Apple ID, your refund requests are handled by Apple, not {$smarty.const.SITE_NAME}. To request a refund, please contact your External Service directly; for example using your Apple device, go to Settings > iTunes & App Stores > [click on your Apple ID] > View Apple ID > Purchase History. Find the transaction and select “Report a Problem.” You can also request a refund at https://getsupport.apple.com. For any other purchase, please contact {$smarty.const.SITE_NAME} Customer Service with your order number (see your confirmation email) by mailing or delivering a signed and dated notice which states that you, the buyer, are canceling this agreement, or words of similar effect. Please also include the email address or telephone number associated with your account along with your order number. This notice shall be sent to: {$smarty.const.SITE_NAME}, Attn: Cancellations, P.O. Box 25472, Dallas, Texas 75225, USA (California and Ohio users may also email us by clicking <a href="/subhelp/" target="_blank">here</a> or send a facsimile to 214-853-4309).</p>
  <h2>8e. INSTALLMENT PLAN CONDITIONS</h2>
  <p><strong><i>If you agree to make a purchase pursuant to the installment plan option, your purchase will be subject to these additional terms and conditions, including around eligibility, payment, and cancellation. </i></strong></p>
  <p>By selecting the option to pay in four payments and clicking subscribe, in addition to the terms set forth above, you agree to the following additional terms that will govern your installment plan purchase:</p>
  <ul>
    <li><p><i>Eligibility</i>.  To be eligible, you must be a {$smarty.const.SITE_NAME} member in good standing residing in the United States of America.  This offer may not be available to every customer and may not be available for all Services {$smarty.const.SITE_NAME} offers.  {$smarty.const.SITE_NAME} will not use a consumer credit report to determine your eligibility for this Agreement.</p></li>
    <li><p><i>Payment</i>.  You authorize {$smarty.const.SITE_NAME} to charge the Payment Method selected on a periodic basis (as determined when you register). You will be charged the full price of the qualifying product you selected spread equally over one initial payment due at the time of purchase and three subsequent payments (provided, however, that if the full price is not evenly divisible by four, your final payment amount may be smaller).The three subsequent payments will be charged in the increments you selected as part of your subscription plan. No interest or finance charges apply to this installment plan purchase.  Any interest, finance charges or fees assessed by the issuer of your Payment Method may still apply.  You are personally responsible for any applicable state, federal or other taxes that may be associated with your purchase of Services unless noted otherwise.</p><p>You can choose to prepay your next schedule payment or the full remaining balance at any time by contacting <a href="/faq/contactus">Customer Care</a>.</p>  </li>
    <li><p><i>{$smarty.const.SITE_NAME}’s right to Terminate</i>.  If {$smarty.const.SITE_NAME} is not able to charge any payment to your Payment Method, {$smarty.const.SITE_NAME} reserves the right to pursue any remedy that is available to it, including the right to suspend or terminate your {$smarty.const.SITE_NAME} subscription and/or {$smarty.const.SITE_NAME} account. You agree that {$smarty.const.SITE_NAME} and its affiliates have no liability related to the exercise of these remedies.</p></li>
    <li><p><i>Cancellation Policy</i>.  Except as otherwise set forth herein, your subscription purchased through your installment plan will continue until terminated, cancelled, or not renewed by you or {$smarty.const.SITE_NAME}, as further described in this Agreement.  If not terminated, cancelled, or not renewed, your Membership will continue to renew with installment payments, until you cancel or change your payment options, via your Account Settings.  If you cancel a subscription, you may continue to use the cancelled service until the end of your then-current subscription term. The subscription will not be renewed when your then-current term expires.  If you cancel your subscription prior to completing all payments due, unless otherwise required by applicable law, the remaining balance of the subscription will remain due and payable pursuant to the installment payment schedule you agreed to.</p></li>
  </ul>
  <h2>9.	ACCOUNT TERMINATION</h2>
  <p><strong><i>If you no longer wish to use our Services, or if we terminate your account for any reason, here’s what you need to know.</i></strong></p>
  <p>You can delete your account at any time by logging into the Website, going to “Settings” (the gear/pencil icon in the top right corner), and following the instructions to cancel your membership. <strong>However, you will need to cancel / manage any External Service Purchases through your External Service Account (e.g., iTunes, Google Play) to avoid additional billing.</strong></p>
  <p>{$smarty.const.SITE_NAME} reserves the right to investigate and, if appropriate, suspend or terminate your account without a refund if you have violated these Terms, misused our Services, or behaved in a way that {$smarty.const.SITE_NAME} regards as inappropriate or unlawful, on or off our Services.  We reserve the right to make use of any personal, technological, legal, or other means available to enforce the Terms, at any time without liability and without the obligation to give you prior notice, including, but not limited to, preventing you from accessing the Services. </p>
  <p>If your account is terminated by you or by {$smarty.const.SITE_NAME} for any reason, these Terms continue and remain enforceable between you and {$smarty.const.SITE_NAME}, and you will not be entitled to any refund for purchases made.  Your information will be maintained and deleted in accordance with our <a href="/legalpolicy/privacypolicy">Privacy Policy</a>.</p>
  <h2>10.	  NO CRIMINAL BACKGROUND OR IDENTITY VERIFICATION CHECKS</h2>
  <p><strong><i>{$smarty.const.SITE_NAME} does not conduct criminal background or identity verification checks on its users. Use your best judgment when interacting with others and check out our <a href="/help/safetytips.aspx?lid=4">Safety Tips</a>.</i></strong></p>
  <p><strong>YOU UNDERSTAND THAT {$smarty.const.SITE_NAME} DOES NOT CONDUCT CRIMINAL BACKGROUND OR IDENTITY VERIFICATION CHECKS ON ITS USERS OR OTHERWISE INQUIRE INTO THE BACKGROUND OF ITS USERS.</strong> {$smarty.const.SITE_NAME} MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT, IDENTITY, INTENTIONS, LEGITIMACY, OR VERACITY OF USERS. {$smarty.const.SITE_NAME} RESERVES THE RIGHT TO CONDUCT—AND YOU AUTHORIZE {$smarty.const.SITE_NAME} TO CONDUCT—ANY CRIMINAL BACKGROUND CHECK OR OTHER SCREENINGS (SUCH AS SEX OFFENDER REGISTER SEARCHES) AT ANY TIME USING AVAILABLE PUBLIC RECORDS, AND YOU AGREE THAT ANY INFORMATION YOU PROVIDE MAY BE USED FOR THAT PURPOSE.  IF THE COMPANY DECIDES TO CONDUCT ANY SCREENING THROUGH A CONSUMER REPORTING AGENCY, YOU HEREBY AUTHORIZE THE COMPANY TO OBTAIN AND USE A CONSUMER REPORT ABOUT YOU TO DETERMINE YOUR ELIGIBILITY UNDER THESE TERMS. </p>
  <p><strong>YOU ARE SOLELY RESPONSIBLE FOR YOUR INTERACTIONS WITH OTHER USERS.</strong> SEX OFFENDER SCREENINGS AND OTHER TOOLS DO NOT GUARANTEE YOUR SAFETY AND ARE NOT A SUBSTITUTE FOR FOLLOWING THE <a href="/help/safetytips.aspx?lid=4">SAFETY TIPS</a> AND OTHER SENSIBLE SAFETY PRECAUTIONS. ALWAYS USE YOUR BEST JUDGMENT AND TAKE APPROPRIATE SAFETY PRECAUTIONS WHEN COMMUNICATING WITH OR MEETING NEW PEOPLE.  COMMUNICATIONS RECEIVED THROUGH THE SERVICE, INCLUDING AUTOMATIC NOTIFICATIONS SENT BY {$smarty.const.SITE_NAME}, MAY RESULT FROM USERS ENGAGING WITH THE SERVICE FOR IMPROPER PURPOSES, INCLUDING FRAUD, ABUSE, HARASSMENT, OR OTHER SUCH IMPROPER BEHAVIOR.</p>
  <p>Though {$smarty.const.SITE_NAME} strives to encourage a respectful user experience, it is not responsible for the conduct of any user on or off the Service. You agree to use caution in all interactions with other users, particularly if you decide to communicate off the Service or meet in person.  </p>
  <h2>11.	DISCLAIMER</h2>
  <p><strong><i>{$smarty.const.SITE_NAME}’s Services are provided “as is” and we do not make, and cannot make, any representations about the content or features of our Services.</i></strong></p>
  <p>{$smarty.const.SITE_NAME} PROVIDES OUR SERVICES ON AN “AS IS” AND “AS AVAILABLE” BASIS AND TO THE EXTENT PERMITTED BY APPLICABLE LAW, GRANTS NO WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE WITH RESPECT TO OUR SERVICES (INCLUDING ALL CONTENT CONTAINED THEREIN), INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF SATISFACTORY QUALITY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. {$smarty.const.SITE_NAME} DOES NOT REPRESENT OR WARRANT THAT (A) OUR SERVICES WILL BE UNINTERRUPTED, SECURE, OR ERROR FREE, (B) ANY DEFECTS OR ERRORS IN OUR SERVICES WILL BE CORRECTED, OR (C) THAT ANY CONTENT OR INFORMATION YOU OBTAIN ON OR THROUGH OUR SERVICES WILL BE ACCURATE. FURTHERMORE, {$smarty.const.SITE_NAME} MAKES NO GUARANTEES AS TO THE NUMBER OF ACTIVE USERS AT ANY TIME; USERS’ ABILITY OR DESIRE TO COMMUNICATE WITH OR MEET YOU, OR THE ULTIMATE COMPATIBILITY WITH OR CONDUCT BY USERS YOU MEET THROUGH THE SERVICES. </p>
  <p>{$smarty.const.SITE_NAME} TAKES NO RESPONSIBILITY FOR ANY CONTENT THAT YOU OR ANOTHER USER OR THIRD PARTY POSTS, SENDS, OR RECEIVES THROUGH OUR SERVICES NOR DOES {$smarty.const.SITE_NAME} TAKE ANY RESPONSIBILITY FOR THE IDENTITY, INTENTIONS, LEGITIMACY, OR VERACITY OF ANY USERS WITH WHOM YOU MAY COMMUNICATION THROUGH {$smarty.const.SITE_NAME}. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF OUR SERVICES IS ACCESSED AT YOUR OWN DISCRETION AND RISK. {$smarty.const.SITE_NAME} IS NOT RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER HARDWARE, COMPUTER SOFTWARE, OR OTHER EQUIPMENT OR TECHNOLOGY INCLUDING, BUT WITHOUT LIMITATION, DAMAGE FROM ANY SECURITY BREACH OR FROM ANY VIRUS, BUGS, TAMPERING, FRAUD, ERROR, OMISSION, INTERRUPTION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER LINE OR NETWORK FAILURE, OR ANY OTHER TECHNICAL OR OTHER MALFUNCTION.</p>
  <h2>12.	DIGITAL MILLENNIUM COPYRIGHT ACT</h2>
  <p><strong><i>We take copyright infringement very seriously. We ask you to help us to ensure we address it promptly and effectively.  </i></strong></p>
  <p>{$smarty.const.SITE_NAME} has adopted the following policy towards copyright infringement in accordance with the Digital Millennium Copyright Act (the “DMCA”). If you believe any Member Content or Our Content infringes upon your intellectual property rights, please submit a notification alleging such infringement (“DMCA Takedown Notice”) including the following:</p>
  <ul>
    <li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>
    <li>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works;</li>
    <li>Identification of the material claimed to be infringing or to be the subject of infringing activity and that is to be removed or access disabled and information reasonably sufficient to permit the service provider to locate the material;</li>
    <li>Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail;</li>
    <li>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</li>
    <li>A statement that, under penalty of perjury, the information in the notification is accurate and you are authorized to act on behalf of the owner of the exclusive right that is allegedly infringed.</li>
  </ul>
  <p>Any DMCA Takedown Notices should be sent to copyright@{$smarty.const.SITE_URL|substr:7}, by phone to 214-576-3272 or via mail to the following address: Copyright Compliance Department c/o {$smarty.const.SITE_NAME} Group Legal, 8750 N. Central Expressway, Dallas, Texas 75231.  </p>
  <p>{$smarty.const.SITE_NAME} will terminate the accounts of repeat infringers.</p>
  <h2>13.	ADS AND THIRD-PARTY CONTENT</h2>
  <p><strong><i>Like many subscription-based services, there are ads on our websites.</i></strong></p>
  <p>Our Services may contain advertisements and promotions offered by third parties and links to other websites or resources. {$smarty.const.SITE_NAME} may also provide non-commercial links or references to third parties within its content. {$smarty.const.SITE_NAME} is not responsible for the availability (or lack of availability) of any external websites or resources or their content. Furthermore, {$smarty.const.SITE_NAME} is not responsible for, and does not endorse, any products or services that may be offered by third-party websites or resources. If you choose to interact with the third parties made available through our Services, such party’s terms will govern their relationship with you. {$smarty.const.SITE_NAME} is not responsible or liable for such third parties’ terms or actions.</p>
  <h2>14.	LIMITATION OF LIABILITY. </h2>
  <p><strong><i>{$smarty.const.SITE_NAME}’s liability is limited to the maximum extent by applicable law.</i></strong></p>
  <p>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL {$smarty.const.SITE_NAME}, ITS AFFILIATES, EMPLOYEES, LICENSORS, OR SERVICE PROVIDERS BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES, INCLUDING, WITHOUT LIMITATION, LOSS OF PROFITS, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM: (I) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES, (II) THE CONDUCT OR CONTENT OF OTHER USERS OR THIRD PARTIES ON, THROUGH, OR FOLLOWING USE OF THE SERVICES; OR (III) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR CONTENT, EVEN IF {$smarty.const.SITE_NAME} HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL {$smarty.const.SITE_NAME}’S AGGREGATE LIABILITY TO YOU FOR ALL CLAIMS RELATING TO THE SERVICES EXCEED THE AMOUNT PAID, IF ANY, BY YOU TO {$smarty.const.SITE_NAME} FOR THE SERVICES WHILE YOU HAVE AN ACCOUNT.</p>
  <p>THE LIMITATION OF LIABILITY PROVISIONS SET FORTH IN THIS SECTION 14 SHALL APPLY EVEN IF YOUR REMEDIES UNDER THIS AGREEMENT FAIL WITH RESPECT TO THEIR ESSENTIAL PURPOSE.</p>
  <p>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES, SO SOME OR ALL OF THE EXCLUSIONS AND LIMITATIONS IN THIS SECTION MAY NOT APPLY TO YOU.</p>
  <h2>15.	DISPUTE RESOLUTION</h2>
  <p><strong><i>In the unlikely event that we have a legal dispute, here is what you need to know.</i></strong></p>
  <p>If you are dissatisfied with our Services for any reason, please contact {$smarty.const.SITE_NAME} Customer Service first so that we can try to resolve your concerns without the need of outside assistance. If you choose to pursue a claim against {$smarty.const.SITE_NAME}, these terms will apply.</p>
  <h3>15a. ARBITRATION, CLASS-ACTION WAIVER, AND JURY WAIVER</h3>
  <p><strong><i>If you pursue a legal claim against {$smarty.const.SITE_NAME}, you agree to arbitration (with limited exceptions). </i></strong></p>
  <ul>
    <li>The exclusive means of resolving any dispute or claim arising out of or relating to this Agreement (including any alleged breach thereof) or our Services shall be BINDING ARBITRATION administered by JAMS under the JAMS Streamlined Arbitration Rules & Procedures, except as modified by our <a href="/legalpolicy/arbitration">Arbitration Procedures</a>. The one exception to the exclusivity of arbitration is that either party has the right to bring an individual claim against the other in a small-claims court of competent jurisdiction, or, if filed in arbitration, the responding party may request that the dispute proceed in small claims court if the party’s claim is within the jurisdiction of the small claims court. If the responding party requests to proceed in small claims court before the appointment of the arbitrator, the arbitration shall be administratively closed, and if requested after the appointment of the arbitrator, the arbitrator shall determine if the dispute should be decided in arbitration or if the arbitration should be administratively closed and decided in small claims court. Whether you choose arbitration or small-claims court, you may not under any circumstances commence or maintain against the Company any class action, class arbitration, or other representative action or proceeding.</li>
    <li>By using our Services in any manner, you agree to the above arbitration agreement. In doing so, YOU GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend any claims between you and the Company (except for matters that may be taken to small-claims court). YOU ALSO GIVE UP YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION OR OTHER CLASS PROCEEDING. Your rights will be determined by a NEUTRAL ARBITRATOR, NOT A JUDGE OR JURY, and the arbitrator shall determine all issues regarding the arbitrability of the dispute. You are entitled to a fair hearing before the arbitrator. The arbitrator can grant any relief that a court can, but you should note that arbitration proceedings are usually simpler and more streamlined than trials and other judicial proceedings. Decisions by the arbitrator are enforceable in court and may be overturned by a court only for very limited reasons. For details on the arbitration process, see our <a href="/legalpolicy/arbitration">Arbitration Procedures.</a></li>
    <li>Any proceeding to enforce this arbitration agreement, including any proceeding to confirm, modify, or vacate an arbitration award, may be commenced in any court of competent jurisdiction. In the event that this arbitration agreement is for any reason held to be unenforceable, any litigation against the Company (except for small-claims court actions) may be commenced only in the federal or state courts located in Dallas County, Texas. You hereby irrevocably consent to the jurisdiction of those courts for such purposes.</li>
  </ul>
  <h2>15b. GOVERNING LAW </h2>
  <p><strong><i>Texas law and the Federal Arbitration Act will apply if there is a dispute (except where prohibited by law).  </i></strong></p>
  <p>Except where our arbitration agreement is prohibited by law, the laws of Texas, U.S.A., excluding Texas’s conflict of laws rules, will apply to any disputes arising out of or relating to this Agreement or our Services. Notwithstanding the foregoing, the Arbitration Agreement in Section 15a above shall be governed by the Federal Arbitration Act. For the avoidance of doubt, the choice of Texas governing law shall not supersede any mandatory consumer protection legislation in such jurisdictions.   </p>
  <h2>15c. VENUE</h2>
  <p><strong><i>Any claims that are not submitted to arbitration for any reason must be litigated in Dallas County, Texas (except for claims brought in small claims court, or where prohibited by law).  </i></strong></p>
  <p>Except for claims that may be properly brought in a small claims court of competent jurisdiction in the county or other jurisdiction in which you reside or in Dallas County, Texas, all claims arising out of or relating to this Agreement, to our Services, or to your relationship with {$smarty.const.SITE_NAME} that for whatever reason are not submitted to arbitration will be litigated exclusively in the federal or state courts of Dallas County, Texas, U.S.A. You and {$smarty.const.SITE_NAME} consent to the exercise of personal jurisdiction of courts in the State of Texas and waive any claim that such courts constitute an inconvenient forum.</p>
  <h2>16.	INDEMNITY BY YOU</h2>
  <p><strong><i>You agree to indemnify {$smarty.const.SITE_NAME} if a claim is made against {$smarty.const.SITE_NAME} due to your actions.</i></strong></p>
  <p>You agree, to the extent permitted under applicable law, to indemnify, defend, and hold harmless {$smarty.const.SITE_NAME}, our affiliates, and their and our respective officers, directors, agents, and employees from and against any and all complaints, demands, claims, damages, losses, costs, liabilities, and expenses, including attorney’s fees, due to, arising out of, or relating in any way to your access to or use of our Services, Your Content, Your conduct toward other users, or your breach of this Agreement.</p>
  <h2>17.	ACCEPTANCE OF TERMS </h2>
  <p><strong><i>By using our Services, you accept the Terms of this Agreement. </i></strong></p>
  <p>By using our Services, whether through a mobile device, mobile application, or computer, you agree to be bound by (i) these Terms, which we may amend from time to time, (ii) our <a href="/legalpolicy/privacypolicy">Privacy Policy</a> and <a href="/legalpolicy/cookiepolicy">Cookie Policy</a>, and (iii) any Additional Terms Upon Purchase. If you do not accept and agree to be bound by all of the terms of this Agreement, please do not use our Services.</p>
  <p>The section headings and summaries contained herein are inserted for convenience only and shall not be considered in interpreting any term or provision hereof. All pronouns and any variations thereof shall be deemed to refer to the masculine, feminine, neuter, singular or plural as the identity of the entities or persons referred to any require. Any word both capitalized and uncapitalized will be deemed to have the same meaning. </p>
  <h2>18. ENTIRE AGREEMENT</h2>
  <p><strong><i>This Agreement supersedes any previous agreements or representations.  </i></strong></p>
  <p>These Terms, with the <a href="/legalpolicy/privacypolicy">Privacy Policy</a>, <a href="/legalpolicy/cookiepolicy">Cookie Policy</a>, and any Additional Terms Upon Purchase, contain the entire agreement between you and {$smarty.const.SITE_NAME} regarding the use of our Services. The Terms supersede all previous agreements, representations, and arrangements between us, written or oral. If any provision of these Terms is held invalid, illegal, or otherwise unenforceable, the remainder of the Terms shall continue in full force and effect. The failure of the Company to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. You agree that your {$smarty.const.SITE_NAME} account is non-transferable and all of your rights to your account and its content terminate upon your death, unless otherwise provided by law. Any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by us without restriction. No agency, partnership, joint venture, fiduciary or other special relationship or employment is created as a result of these Terms, and you may not make any representations on behalf of or bind {$smarty.const.SITE_NAME} in any manner. </p>
  <h2>19.	SPECIAL STATE TERMS</h2>
  <p><strong><i>Special terms apply in Arizona, California, Connecticut, Illinois, Iowa, Minnesota, New York, North Carolina, Ohio, Rhode Island, Wisconsin</i></strong></p>
  <p class="underline">For subscribers residing in New York:</p>
  <ul class="bullet">
    <li>The Services do not guarantee any number of “referrals”—rather, the functionality of the Services is such that the subscriber can view as many profiles as he/she would like;</li>
    <li>Upon notice in writing and delivered to {$smarty.const.SITE_NAME} Group Legal, P.O. Box 25472, Dallas, Texas 75225, USA, subscribers may place their subscription on hold for up to one year;</li>
    <li>How your information is used and how you may access your information is set forth in our <a href="/legalpolicy/privacypolicy">Privacy Policy</a>;</li>
    <li>You may review the New York Dating Service Consumer Bill of Rights <a href="https://www.nysenate.gov/legislation/laws/GBS/394-C">here</a>; </li>
  </ul>
  <p class="underline">For subscribers residing in North Carolina:</p>
  <ul class="bullet">
    <li>You may review the North Carolina Buyer’s Rights <a href="https://www.ncleg.gov/EnactedLegislation/Statutes/PDF/BySection/Chapter_66/GS_66-120.pdf">here</a>.</li>
  </ul>
  <p class="underline">For subscribers residing in Illinois, New York, North Carolina, and Ohio :</p>
  <ul class="bullet">
    <li>Our Services are widely available in the United States—if you believe that you have moved outside a location where we provide the Services, please contact us in writing delivered to {$smarty.const.SITE_NAME} Group Legal, P.O. Box 25472, Dallas, Texas 75225, USA, and we will work with you to provide alternative services or a refund.</li>
  </ul>
  <p class="underline">For subscribers residing in Arizona, California, Connecticut, Illinois, Iowa, Minnesota, New York, North Carolina, Ohio, Rhode Island, and Wisconsin:</p>
  <p><strong>Your Right to Cancel—You may cancel your subscription, without penalty or obligation, at any time prior to midnight of the third business day following the date you subscribed.</strong> In the event that you die before the end of your subscription period, your estate shall be entitled to a refund of that portion of any payment you had made for your subscription which is allocable to the period after your death. In the event that you become disabled (such that you are unable to use our Services) before the end of your subscription period, you shall be entitled to a refund of that portion of any payment you had made for your subscription which is allocable to the period after your disability by providing the company notice in the same manner as you request a refund as described above in Section 8.</p>
</div>
</div>


</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>